### ISSUE TITLE
FileNotFoundException while opening Veccy on Windows

### ISSUE THREAD

**Issue by mountaingoate** [malbanGit/Vide#4]
Probably nothing serious but Veccy throws an exception about trying to open a Sql file on Windows:

Database 'MacOneClickDB' not found.
DB does not exist!
Error reading file.
java.io.FileNotFoundException: .\src_db\dbCreate.sql (The system cannot find the
 path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at de.malban.util.UtilityString.readTextFileToString(UtilityString.java: 511)
        at de.malban.util.UtilityString.replaceToNewFile(UtilityString.java:585)
        at de.malban.vide.DBSupport.createDB(DBSupport.java:90)
        at de.malban.vide.VeccyPanel.<init>(VeccyPanel.java:118)

**Comment by malbanGit** [comment]
Ah, yeah...
This is "unfinished code" the exception is thrown, but you should not be bothered.
The idea was to create a database, where all the "knowledge" gathered should be stored and retrieved from. I should comment out the stuff that behaves badly... 
Hm, or I could just bundle the sql with VIDE, it is empty now anyway :-)...

What ever I do, will be gone with next update - and you shouldn't be bothered. But thanks for mentioning.
